Add navbar
Anonymous-Voting-App/Anonymous-Voting-App pull request #64
Opened 2022-10-04 20:06 UTC by oonasaksman

### Add navbar #55

## Describe your changes

Implemented navbar component. Simple code so no comments.

## Checklist before requesting a review

-   [ x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added thorough tests

2022-10-06 09:10 UTC, Marakke requested changes
The Header component should probably be removed now that the NavBar is implemented.

2022-10-06 09:12 UTC, Marakke requested changes

2022-10-06 09:12 UTC, Marakke commented on frontend/src/components/NavBar.tsx
> +            style={{ backgroundColor: '#333333', position: 'relative' }}
This styling should be moved to the SCSS file.

2022-10-06 09:12 UTC, Marakke commented on frontend/src/components/NavBar.tsx
> +                style={{ fontSize: 40, color: '#333333' }}
Same here, move this to SCSS.

2022-10-06 09:18 UTC, Marakke commented on frontend/src/components/NavBar.tsx
> +            style={{ backgroundColor: '#333333', position: 'relative' }}
Also, you should `@import '../styles/_colors';` and use the color variables defined there. No need to define them in each file.

2022-10-06 09:41 UTC, vrindavj commented on frontend/src/components/App.tsx
>              <Header></Header>
Header component can be removed as we have navabar

2022-10-06 09:42 UTC, vrindavj approved these changes
Rest everything looks good to me.:)

2022-10-06 12:38 UTC, Marakke submitted a review, later dismissed

2022-10-06 13:00 UTC, Marakke submitted a review, later dismissed

2022-10-06 14:42 UTC, Marakke submitted a review, later dismissed

2022-10-06 14:46 UTC, vrindavj approved these changes
header component is removed and code is working fine👍🏻

2022-10-07 07:22 UTC, Jontzii commented
Fixed rebase issue

2022-10-10 08:37 UTC, Marakke approved these changes

2022-10-10 08:44 UTC, JeToKo approved these changes
Looks good

2022-10-10 08:46 UTC, merged